"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT")



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"
# ALLOWED_HOSTS configuration
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "*")
if allowed_hosts_env == "*":
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",")]



# Application definition
INSTALLED_APPS = [
    "corsheaders",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "api",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]



# CORS settings
cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(",")]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# Allow custom tenant headers for cross-origin requests
CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-Tenant",
    "X-Tenant-Id",
]

# Frontend URL for generating signature links

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for simplicity (can be committed to GitHub)
# For production, you can switch to PostgreSQL if needed
USE_SQLITE = os.environ.get("USE_SQLITE", "True").lower() == "true"

if USE_SQLITE:
    # SQLite configuration (simple, file-based database)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # PostgreSQL configuration (for production hosting)
    try:
        import dj_database_url
    except ImportError:
        dj_database_url = None
    
    DATABASE_URL = os.environ.get("DATABASE_URL")
    
    if DATABASE_URL and dj_database_url:
        # Use DATABASE_URL if provided (Railway, Render, Heroku, etc.)
        DATABASES = {
            "default": dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    else:
        # Fallback to individual environment variables
        _db_config_base = {
            "ENGINE": "django.db.backends.postgresql",
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }

        DATABASES = {
            "default": {
                **_db_config_base,
                "NAME": os.environ.get("POSTGRES_DB", "bedelias-api"),
                "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
            },
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# drf-spectacular (OpenAPI/Swagger) configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Bedelia',
    'DESCRIPTION': '''
    API de Gestión de Cursos de Bedelia
    
    Esta API proporciona acceso a datos de cursos universitarios incluyendo:
    - **Carreras**: Programas de grado académico
    - **Materias**: Cursos/asignaturas con códigos y créditos
    - **Planes de Estudio**: Planes de estudio para cada carrera
    - **Unidades Aprobables**: Unidades aprobables (cursos, exámenes, módulos)
    - **Requisitos**: Árboles de requisitos previos con operadores lógicos (AND, OR, NOT)
    
    ## Estructura de Datos:
    - Cada **Carrera** (programa de grado) tiene múltiples **Planes de Estudio**
    - Cada **Plan de Estudio** contiene múltiples **Materias** (cursos)
    - Cada **Materia** puede tener múltiples **Unidades Aprobables** (unidades aprobables)
    - Cada **PlanMateria** tiene una estructura de árbol **RequisitoNodo** que define los requisitos previos
    - Los **RequisitoNodos** pueden ser de tipo ROOT, AND, OR, NOT o LEAF
    - Los nodos **LEAF** contienen **RequisitoItems** que especifican los requisitos reales
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api',
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Servidor de desarrollo'},
    ],
    'TAGS': [
        {'name': 'carreras', 'description': 'Programas de grado académico (carreras)'},
        {'name': 'materias', 'description': 'Cursos/asignaturas (materias)'},
        {'name': 'planes-estudio', 'description': 'Planes de estudio'},
        {'name': 'planes-materias', 'description': 'Materias dentro de los planes de estudio'},
        {'name': 'unidades-aprobables', 'description': 'Unidades aprobables'},
        {'name': 'requisitos', 'description': 'Requisitos de cursos y requisitos previos'},
        {'name': 'previas', 'description': 'Requisitos previos (previas) para PlanMaterias'},
        {'name': 'posprevias', 'description': 'Cursos dependientes (posprevias) que requieren una PlanMateria'},
    ],
    'ENUM_NAME_OVERRIDES': {
        'UnidadAprobableTipoEnum': 'api.models.UnidadAprobable.Tipo',
        'RequisitoNodoTipoEnum': 'api.models.RequisitoNodo.Tipo',
        'RequisitoItemTipoEnum': 'api.models.RequisitoItem.TipoItem',
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'defaultModelRendering': 'model',
        'displayRequestDuration': True,
        'docExpansion': 'list',  # 'none', 'list', or 'full'
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
        'persistAuthorization': False,
    },
}


# Logging configuration for S3 operations
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    }
}
