# Generated by Django 5.2.7 on 2025-11-16 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la materia')),
                ('creditos', models.IntegerField(default=0, verbose_name='Créditos de referencia')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(db_index=True, max_length=255, verbose_name='Nombre de la carrera')),
                ('anio', models.CharField(max_length=10, verbose_name='Año del plan')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de estudio',
                'verbose_name_plural': 'Planes de estudio',
                'db_table': 'planes_estudio',
                'indexes': [models.Index(fields=['nombre_carrera', 'anio'], name='idx_plan_carrera_anio')],
                'unique_together': {('nombre_carrera', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='PlanMateria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='api.materia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_plan', to='api.planestudio')),
            ],
            options={
                'verbose_name': 'Materia en plan',
                'verbose_name_plural': 'Materias en plan',
                'db_table': 'planes_materias',
            },
        ),
        migrations.CreateModel(
            name='RequisitoNodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ALL', 'Debe cumplir todas'), ('ANY', 'Debe cumplir alguna'), ('NOT', 'No debe cumplir'), ('LEAF', 'Condición hoja')], max_length=10, verbose_name='Tipo de nodo')),
                ('cantidad_minima', models.IntegerField(blank=True, null=True, verbose_name='Cantidad mínima (para ANY)')),
                ('orden', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción / texto auxiliar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='api.requisitonodo', verbose_name='Nodo padre')),
                ('plan_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='api.planmateria', verbose_name='Materia en plan a la que aplica')),
            ],
            options={
                'verbose_name': 'Nodo de requisito',
                'verbose_name_plural': 'Nodos de requisitos',
                'db_table': 'requisitos_nodos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAprobable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('EXAMEN', 'Examen'), ('UCB', 'Módulo/UCB'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de unidad')),
                ('codigo_bedelias', models.CharField(blank=True, max_length=50, verbose_name='Código Bedelías / identificador externo')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre descriptivo (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='api.materia')),
            ],
            options={
                'verbose_name': 'Unidad aprobable',
                'verbose_name_plural': 'Unidades aprobables',
                'db_table': 'unidades_aprobables',
            },
        ),
        migrations.CreateModel(
            name='RequisitoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('UNIDAD', 'Unidad aprobable específica'), ('CREDITOS', 'Créditos mínimos'), ('TEXTO', 'Condición libre')], max_length=20, verbose_name='Tipo de condición')),
                ('creditos_minimos', models.IntegerField(blank=True, null=True, verbose_name='Créditos mínimos requeridos')),
                ('texto', models.CharField(blank=True, max_length=500, verbose_name='Descripción textual')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.requisitonodo', verbose_name='Nodo LEAF')),
                ('unidad_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='como_requisito', to='api.unidadaprobable', verbose_name='Unidad requerida')),
            ],
            options={
                'verbose_name': 'Item de requisito',
                'verbose_name_plural': 'Items de requisitos',
                'db_table': 'requisitos_items',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='planmateria',
            index=models.Index(fields=['plan'], name='idx_plan_materia_plan'),
        ),
        migrations.AddIndex(
            model_name='planmateria',
            index=models.Index(fields=['materia'], name='idx_plan_materia_materia'),
        ),
        migrations.AlterUniqueTogether(
            name='planmateria',
            unique_together={('plan', 'materia')},
        ),
        migrations.AddIndex(
            model_name='requisitonodo',
            index=models.Index(fields=['plan_materia'], name='idx_req_plan_materia'),
        ),
        migrations.AddIndex(
            model_name='requisitonodo',
            index=models.Index(fields=['padre'], name='idx_req_padre'),
        ),
        migrations.AddIndex(
            model_name='requisitonodo',
            index=models.Index(fields=['tipo'], name='idx_req_tipo'),
        ),
        migrations.AddIndex(
            model_name='unidadaprobable',
            index=models.Index(fields=['materia'], name='idx_unidad_materia'),
        ),
        migrations.AddIndex(
            model_name='unidadaprobable',
            index=models.Index(fields=['tipo'], name='idx_unidad_tipo'),
        ),
        migrations.AddIndex(
            model_name='requisitoitem',
            index=models.Index(fields=['nodo', 'orden'], name='idx_req_item_nodo_orden'),
        ),
    ]
