# Generated by Django 5.2.7 on 2025-11-07 08:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('COURSE', 'Course'), ('EXAM', 'Exam')], help_text='Type of offering: COURSE or EXAM', max_length=10)),
                ('term', models.CharField(blank=True, help_text='Academic term (e.g., 2025S1, 2024S2)', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='term must look like 2025S1 or 2024S2', regex='^\\d{4}S[12]$')])),
                ('section', models.CharField(blank=True, help_text='Section identifier', max_length=32, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, help_text='Semester number (1, 2, or 3)', null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, help_text='Number of credits for this offering', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offering is currently active')),
                ('url_source', models.URLField(blank=True, help_text='Source URL for this offering', max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, help_text='Last time data was scraped', null=True)),
                ('html_hash', models.CharField(blank=True, help_text='Hash of scraped HTML content', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
                'db_table': 'offerings',
                'ordering': ['-term', 'subject__code', 'type', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the academic program', max_length=255)),
                ('plan_year', models.IntegerField(blank=True, help_text='Year the plan was established', null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['plan_year', 'name'],
                'indexes': [models.Index(fields=['plan_year'], name='idx_program_year')],
            },
        ),
        migrations.CreateModel(
            name='RequirementGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('NONE', 'NONE')], help_text='Scope: ALL (all required), ANY (min_required), or NONE (forbidden)', max_length=8)),
                ('flavor', models.CharField(choices=[('GENERIC', 'GENERIC'), ('APPROVALS', 'APPROVALS'), ('ACTIVITIES', 'ACTIVITIES'), ('COURSE_APPROVED', 'COURSE_APPROVED'), ('COURSE_ENROLLED', 'COURSE_ENROLLED'), ('EXAM_APPROVED', 'EXAM_APPROVED'), ('EXAM_ENROLLED', 'EXAM_ENROLLED'), ('COURSE_CREDITED', 'COURSE_CREDITED'), ('EXAM_CREDITED', 'EXAM_CREDITED')], default='GENERIC', help_text='Semantic flavor of this requirement group', max_length=32)),
                ('min_required', models.PositiveIntegerField(blank=True, help_text='Minimum items required (only for ANY scope)', null=True)),
                ('note', models.CharField(blank=True, help_text='Additional notes or clarifications', max_length=500, null=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order within the offering')),
                ('offering', models.ForeignKey(help_text='Offering these requirements apply to', on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='api.offering')),
            ],
            options={
                'verbose_name': 'Requirement Group',
                'verbose_name_plural': 'Requirement Groups',
                'db_table': 'requirement_groups',
                'ordering': ['offering', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='RequirementGroupLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order of child within parent')),
                ('child_group', models.ForeignKey(help_text='Child requirement group', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='api.requirementgroup')),
                ('parent_group', models.ForeignKey(help_text='Parent requirement group', on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='api.requirementgroup')),
            ],
            options={
                'verbose_name': 'Requirement Group Link',
                'verbose_name_plural': 'Requirement Group Links',
                'db_table': 'requirement_group_links',
                'ordering': ['parent_group', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Subject code (e.g., UCB/FIng code)', max_length=16, unique=True)),
                ('name', models.CharField(help_text='Full name of the subject', max_length=255)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, help_text='Number of credits for this subject', max_digits=6, null=True)),
                ('dept', models.CharField(blank=True, default='', help_text='Department offering this subject', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subject', null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, help_text='Recommended semester (1 or 2)', null=True)),
                ('programs', models.ManyToManyField(blank=True, help_text='Academic programs this subject belongs to', related_name='subjects', to='api.program')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('SUBJECT', 'SUBJECT'), ('OFFERING', 'OFFERING')], help_text='Type of target: SUBJECT or OFFERING', max_length=16)),
                ('condition', models.CharField(choices=[('APPROVED', 'APPROVED'), ('ENROLLED', 'ENROLLED'), ('CREDITED', 'CREDITED')], default='APPROVED', help_text='Required condition: APPROVED, ENROLLED, or CREDITED', max_length=16)),
                ('alt_code', models.CharField(blank=True, help_text='Fallback code if ID not resolved', max_length=50, null=True)),
                ('alt_label', models.CharField(blank=True, help_text='Display label for this item', max_length=255, null=True)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order within the group')),
                ('group', models.ForeignKey(help_text='Requirement group this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.requirementgroup')),
                ('target_offering', models.ForeignKey(blank=True, help_text='Target offering (if target_type is OFFERING)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offering')),
                ('target_subject', models.ForeignKey(blank=True, help_text='Target subject (if target_type is SUBJECT)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'verbose_name': 'Requirement Item',
                'verbose_name_plural': 'Requirement Items',
                'db_table': 'requirement_items',
                'ordering': ['group', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='offering',
            name='subject',
            field=models.ForeignKey(help_text='Subject this offering is for', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.subject'),
        ),
        migrations.CreateModel(
            name='DependencyEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_type', models.CharField(choices=[('SUBJECT', 'SUBJECT'), ('OFFERING', 'OFFERING')], help_text='Type of source: SUBJECT or OFFERING', max_length=16)),
                ('kind', models.CharField(choices=[('REQUIRES_ALL', 'REQUIRES_ALL'), ('ALTERNATIVE_ANY', 'ALTERNATIVE_ANY'), ('FORBIDDEN_NONE', 'FORBIDDEN_NONE')], help_text='Type of dependency: REQUIRES_ALL, ALTERNATIVE_ANY, or FORBIDDEN_NONE', max_length=32)),
                ('condition', models.CharField(choices=[('APPROVED', 'APPROVED'), ('ENROLLED', 'ENROLLED'), ('CREDITED', 'CREDITED')], default='APPROVED', help_text='Required condition for the dependency', max_length=16)),
                ('from_offering', models.ForeignKey(blank=True, help_text='Source offering (if from_type is OFFERING)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_out_offering', to='api.offering')),
                ('to_offering', models.ForeignKey(help_text='Target offering that has this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dep_in', to='api.offering')),
                ('group', models.ForeignKey(help_text='Requirement group this dependency comes from', on_delete=django.db.models.deletion.CASCADE, related_name='dependency_edges', to='api.requirementgroup')),
                ('from_subject', models.ForeignKey(blank=True, help_text='Source subject (if from_type is SUBJECT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_out_subject', to='api.subject')),
            ],
            options={
                'verbose_name': 'Dependency Edge',
                'verbose_name_plural': 'Dependency Edges',
                'db_table': 'dependency_edges',
                'ordering': ['to_offering', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_code', models.CharField(blank=True, help_text='Alternative code for the subject', max_length=50, null=True)),
                ('alias_name', models.CharField(blank=True, help_text='Alternative name for the subject', max_length=255, null=True)),
                ('subject', models.ForeignKey(help_text='Subject this alias refers to', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.subject')),
            ],
            options={
                'verbose_name': 'Subject Alias',
                'verbose_name_plural': 'Subject Aliases',
                'db_table': 'subject_aliases',
                'ordering': ['subject', 'alias_code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectEquivalence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('FULL', 'Full Equivalence'), ('PARTIAL', 'Partial Equivalence')], help_text='Type of equivalence: FULL or PARTIAL', max_length=16)),
                ('note', models.CharField(blank=True, help_text='Additional notes about the equivalence', max_length=500, null=True)),
                ('subject_a', models.ForeignKey(help_text='First subject in the equivalence relationship', on_delete=django.db.models.deletion.CASCADE, related_name='equiv_as_a', to='api.subject')),
                ('subject_b', models.ForeignKey(help_text='Second subject in the equivalence relationship', on_delete=django.db.models.deletion.CASCADE, related_name='equiv_as_b', to='api.subject')),
            ],
            options={
                'verbose_name': 'Subject Equivalence',
                'verbose_name_plural': 'Subject Equivalences',
                'db_table': 'subject_equivalences',
                'ordering': ['subject_a', 'subject_b'],
            },
        ),
        migrations.CreateModel(
            name='AuditSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='URL of the scraped page', max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When the data was fetched')),
                ('status', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code of the request', null=True)),
                ('html_checksum', models.CharField(blank=True, help_text='Checksum of the HTML content', max_length=64, null=True)),
                ('parsed_ok', models.BooleanField(blank=True, help_text='Whether parsing was successful', null=True)),
                ('raw_snapshot', models.BinaryField(blank=True, help_text='Raw HTML snapshot (consider external storage for large files)', null=True)),
                ('offering', models.ForeignKey(blank=True, help_text='Associated offering (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offering')),
            ],
            options={
                'verbose_name': 'Audit Source',
                'verbose_name_plural': 'Audit Sources',
                'db_table': 'audit_sources',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['offering'], name='idx_audit_offering'), models.Index(fields=['fetched_at'], name='idx_audit_time'), models.Index(fields=['status'], name='idx_audit_status'), models.Index(fields=['parsed_ok'], name='idx_audit_parsed')],
            },
        ),
        migrations.CreateModel(
            name='OfferingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text='Type of link (e.g., syllabus, moodle, slides)', max_length=32)),
                ('url', models.URLField(help_text='URL of the resource', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Display title for the link', max_length=255, null=True)),
                ('offering', models.ForeignKey(help_text='Offering this link is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.offering')),
            ],
            options={
                'verbose_name': 'Offering Link',
                'verbose_name_plural': 'Offering Links',
                'db_table': 'offering_links',
                'ordering': ['offering', 'kind'],
                'indexes': [models.Index(fields=['offering'], name='idx_offering_links_offering'), models.Index(fields=['kind'], name='idx_offering_links_kind')],
            },
        ),
        migrations.AddIndex(
            model_name='requirementgroup',
            index=models.Index(fields=['offering', 'order_index'], name='idx_req_groups_offering'),
        ),
        migrations.AddConstraint(
            model_name='requirementgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'ANY'), ('min_required__gte', 1)), models.Q(('scope__in', ['ALL', 'NONE']), ('min_required__isnull', True)), _connector='OR'), name='ck_group_min_required_semantics'),
        ),
        migrations.AddIndex(
            model_name='requirementgrouplink',
            index=models.Index(fields=['parent_group', 'order_index'], name='idx_req_group_links_parent'),
        ),
        migrations.AddIndex(
            model_name='requirementgrouplink',
            index=models.Index(fields=['child_group'], name='idx_req_group_links_child'),
        ),
        migrations.AddConstraint(
            model_name='requirementgrouplink',
            constraint=models.UniqueConstraint(fields=('parent_group', 'child_group'), name='uq_group_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='requirementgrouplink',
            constraint=models.CheckConstraint(condition=models.Q(('parent_group', models.F('child_group')), _negated=True), name='ck_group_no_self_link'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='idx_subjects_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('semester__in', [1, 2]), ('semester__isnull', True), _connector='OR'), name='ck_subject_semester_in_1_2_or_null'),
        ),
        migrations.AddIndex(
            model_name='requirementitem',
            index=models.Index(fields=['group', 'order_index'], name='idx_req_items_group'),
        ),
        migrations.AddIndex(
            model_name='requirementitem',
            index=models.Index(fields=['target_subject'], name='idx_req_items_target_subj'),
        ),
        migrations.AddIndex(
            model_name='requirementitem',
            index=models.Index(fields=['target_offering'], name='idx_req_items_target_off'),
        ),
        migrations.AddIndex(
            model_name='requirementitem',
            index=models.Index(fields=['condition'], name='idx_req_items_condition'),
        ),
        migrations.AddConstraint(
            model_name='requirementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'SUBJECT'), ('target_subject__isnull', False), ('target_offering__isnull', True)), models.Q(('target_type', 'OFFERING'), ('target_offering__isnull', False), ('target_subject__isnull', True)), _connector='OR'), name='ck_item_target_exclusive'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['subject'], name='idx_offerings_subject'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['type', 'term'], name='idx_offerings_type_term'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['is_active'], name='idx_offerings_active'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['semester'], name='idx_offerings_semester'),
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.UniqueConstraint(fields=('subject', 'type', 'term', 'section'), name='uq_offering_unique'),
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.CheckConstraint(condition=models.Q(('semester__in', [1, 2, 3]), ('semester__isnull', True), _connector='OR'), name='ck_offering_semester_in_1_2_3_or_null'),
        ),
        migrations.AddIndex(
            model_name='dependencyedge',
            index=models.Index(fields=['from_subject'], name='idx_dep_from_subject'),
        ),
        migrations.AddIndex(
            model_name='dependencyedge',
            index=models.Index(fields=['from_offering'], name='idx_dep_from_off'),
        ),
        migrations.AddIndex(
            model_name='dependencyedge',
            index=models.Index(fields=['to_offering'], name='idx_dep_to_offering'),
        ),
        migrations.AddIndex(
            model_name='dependencyedge',
            index=models.Index(fields=['kind'], name='idx_dep_kind'),
        ),
        migrations.AddIndex(
            model_name='dependencyedge',
            index=models.Index(fields=['condition'], name='idx_dep_condition'),
        ),
        migrations.AddConstraint(
            model_name='dependencyedge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_type', 'SUBJECT'), ('from_subject__isnull', False), ('from_offering__isnull', True)), models.Q(('from_type', 'OFFERING'), ('from_offering__isnull', False), ('from_subject__isnull', True)), _connector='OR'), name='ck_dep_from_target_exclusive'),
        ),
        migrations.AddIndex(
            model_name='subjectalias',
            index=models.Index(fields=['alias_code'], name='idx_alias_code'),
        ),
        migrations.AddIndex(
            model_name='subjectalias',
            index=models.Index(fields=['alias_name'], name='idx_alias_name'),
        ),
        migrations.AddConstraint(
            model_name='subjectalias',
            constraint=models.UniqueConstraint(fields=('subject', 'alias_code'), name='uq_alias_code_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='subjectalias',
            constraint=models.UniqueConstraint(fields=('subject', 'alias_name'), name='uq_alias_name_per_subject'),
        ),
        migrations.AddIndex(
            model_name='subjectequivalence',
            index=models.Index(fields=['subject_a'], name='idx_equiv_subject_a'),
        ),
        migrations.AddIndex(
            model_name='subjectequivalence',
            index=models.Index(fields=['subject_b'], name='idx_equiv_subject_b'),
        ),
        migrations.AddIndex(
            model_name='subjectequivalence',
            index=models.Index(fields=['kind'], name='idx_equiv_kind'),
        ),
        migrations.AddConstraint(
            model_name='subjectequivalence',
            constraint=models.CheckConstraint(condition=models.Q(('subject_a', models.F('subject_b')), _negated=True), name='ck_equiv_not_self'),
        ),
    ]
