# Generated by Django 5.2.7 on 2025-11-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitonodo',
            name='unidad_tipo',
            field=models.CharField(blank=True, help_text='Tipo de UnidadAprobable al que aplican estos requisitos', max_length=20, verbose_name='Tipo de unidad (CURSO, EXAMEN, etc.)'),
        ),
        migrations.AddIndex(
            model_name='requisitonodo',
            index=models.Index(fields=['plan_materia', 'unidad_tipo'], name='idx_req_pm_unidad'),
        ),
    ]
