# Generated by Django 4.2.6 on 2025-11-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planmateria',
            options={'verbose_name': 'Plan-Materia', 'verbose_name_plural': 'Plan-Materias'},
        ),
        migrations.AddField(
            model_name='planmateria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='api.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='planmateria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_plan', to='api.planestudio', verbose_name='Plan de estudio'),
        ),
        migrations.AlterModelTable(
            name='planmateria',
            table='plan_materias',
        ),
    ]
