# Generated by Django 5.2.7 on 2025-11-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='ck_subject_semester_in_1_2_or_null',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
