# Generated by Django 4.2.6 on 2025-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_evaluacion',
            field=models.CharField(blank=True, choices=[('Curso', 'Curso'), ('Examen', 'Examen'), ('', 'No especificado')], default='', max_length=10, verbose_name='Tipo de Evaluación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código de Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_universidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Universidad'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo_curso', 'tipo_evaluacion')},
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['tipo_evaluacion'], name='idx_tipo_evaluacion'),
        ),
    ]
